spring.application.name=Votezy
spring.datasource.url=jdbc:mysql://localhost:3306/votezy_db
spring.datasource.username=root
spring.datasource.password=eshu@12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9091

# ✅ NEW: JWT Secret Key (change this to any long random string in production)
jwt.secret=&@#*$sdfdc dfddhhrvrdgr&@#*$#&$#@e cjdkfhj#@&*$#@^$@#fjdhgfhkreroifew127323432649832895N&#*$532sdjfs ver*(#&@84932tddkjfdskf
jwt.expiration=86400000
 
# ✅ NEW: Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html